as yet unclassified
with: anException
	^ self new
		exception: anException;
		yourself